### ISSUE TITLE
Source Code View: new flags for `sl analyze`

### ISSUE THREAD

**Issue by khorne3** [ShiftLeftSecurity/documentation#261]

**Comment by khorne3** [comment]
[Product ETA 3/19](https://app.zenhub.com/workspaces/product-595055eb7206ea01d3e05259/issues/shiftleftsecurity/product/3582

**Comment by perrito666** [comment]
With the inclusion of VCS links, `sl analyze` gained two new flags, feel free to reach me to give as much detail as you may require for this.

In short, this works only for GIT right now, if the `sl analyze` commandis invoked inside a git repo (either root of the repo or any subfolder) the `remote` named `origin` is sent to shiftleft as metadata for the analysis, this is used to later display links to the repo in the data flow view.

If `--no-vcs-metadata` is specified no data is sent. if `--git-remote-name` is specified whatever string is passed there is used instead of `origin`, nothing happens if either the remote or the repo are not found.

```
--no-vcs-metadata           When this flag is not specified, VCS metadata (remote origin if found) is sent to our servers to generate VCS links to the vulnerabilities
--git-remote-name           When passed, this value is used instead of origin as the expected default remote when sending Git VCS metadata for an analysis
```
